---
# vars file for eks_cluster
namespace_name: elastic
cluster_name: picnic
region: us-east-1
ssh_key_name: italo
zones: 'us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1f'
instance_type: m5.large
profile: italo
node_storage: 50
node_min: 2
node_max: 4

crds_operator:
  - https://download.elastic.co/downloads/eck/1.8.0/crds.yaml
  - https://download.elastic.co/downloads/eck/1.8.0/operator.yaml

metric_server:
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  - https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.5/aio/deploy/recommended.yaml

resources:
  - namespace.yml
  - storageClass.yml
  - eks-admin-service-account.yml