---
# vars file for create-instances
sec_group_name: k8s
instance_type: t3.medium
ami_id: ami-09e67e426f25ce0d7
profile: italo
region: us-east-1
keypair: italo
count: 3
device_name: /dev/sdb
volume_type: gp2
volume_size: 25
